# Generated by Django 3.1.7 on 2021-05-27 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('office', '0003_auto_20210525_2011'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='role',
            name='desc',
        ),
    ]
