# Generated by Django 3.1.7 on 2021-05-29 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('office', '0004_remove_role_desc'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gmail',
            name='file',
        ),
        migrations.AlterField(
            model_name='gmail',
            name='subject',
            field=models.CharField(max_length=10000),
        ),
    ]
